#remote_theme: beAuthentic/askclass-course-theme
#theme: askclass-course-theme

title: "Kairos Church History"
description: >
  This is a survey of the history of the church from the
  early church to the end of the Middle Ages.

acc:
  date_format: "%b %d, %y"
  short_name: "CH-525"
  color:
    theme: "#2cdd88"
    bg: "#2a2a2a"
  url: "https://ch525.nissi.app"
  categories:
    - education
  logo:
    image: "logo.svg"
    size: 70
    height: 70
    alt_image: "logo.svg"
    alt_size: 200
    sizes: [ 48, 96, 144, 192, 300, 512, 800, 1024 ]
  meta:
    apple_icon: "logo-square-300.png"
    og_image: "logo-square-512.png"
    shortcut:
      favicon: "favicon.ico"
      type: "image/png"
      image: "logo-96.png"
    keywords: >
      education,
      learning,
      theology,
      psychology,
      christianity
  footer:
    - icon: "attribution"
      href: "https://acc.askclass.com"
      text: "AskClass Template"
  # Donot change the below (will figure something out later)
  font_families:
    - Teko
    - Open+Sans
    - Josefin+Sans
    - Share+Tech+Mono
    - Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200

collections_dir: content
collections:
  session:
    output: true
  segment:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "session"
    values:
      layout: "session"
  - scope:
      type: "segment"
    values:
      layout: "segment"

exclude:
  - CNAME
  - runme.sh
